version: "3.8"
services:

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: immersion
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=immersion;Username=postgres;Password=secret"
    entrypoint: >
      sh -c "
        dotnet ef database update --no-build &&
        dotnet ImmersionAI.API.dll
      "
    ports:
      - "5000:80"

volumes:
  db_data:
